### ISSUE TITLE
There is no moveit_msgsConfig

### ISSUE THREAD

**Issue by hihixuyang** [diogoalmeida/sarafun_msgs#1]
Dear author,

I found there is no moveit_msgsConfig.

**Comment by diogoalmeida** [comment]
Hi @hihixuyang,

You should be able to get moveit messages if you install the [moveit ros package](http://moveit.ros.org/install/).

**Comment by hihixuyang** [comment]
Hi, thx a lot! I have fixed these problems. Your design is perfect!
